<?php
return array (
  84 => 
  array (
    'id' => '84',
    'catid' => '9',
    'typeid' => '',
    'title' => '漫畫介紹─偽姬日常(01)',
    'style' => '',
    'thumb' => 'http://pic2.mofang.com/2015/1013/20151013094325449.jpg',
    'keywords' => 'ひめゴト,偽姬日常,佃煮のりお',
    'description' => '漫畫介紹─偽姬日常 （01）（ひめゴト 01）　　《偽姬日常》是由「佃煮のりお」老師所繪製的四格漫畫作品，這次要介紹的第一集，其實於 ...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/comic/9-84-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443416429',
    'updatetime' => '1444128597',
    'authorname' => '夢燁',
    'shortname' => '',
    'hitsid' => 'c-1-84',
    'views' => '10',
    'yesterdayviews' => '3',
    'dayviews' => '2',
    'weekviews' => '5',
    'monthviews' => '9',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '9',
    'typeid' => '59,60',
    'title' => '漫畫介紹－學戰都市 Asterrisk （01）',
    'style' => '',
    'thumb' => 'http://pic2.mofang.com/2015/1013/20151013093138340.jpg',
    'keywords' => '學戰都市,Asterrisk,アスタリスク,学戦都市',
    'description' => '漫畫介紹－學戰都市 Asterrisk （01）（学戦都市アスタリスク　01）　　《學戰都市 Asterisk》原作是輕小說由三屋咲悠老師所著，而漫畫...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/comic/9-67-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443415896',
    'updatetime' => '1447319351',
    'authorname' => '洛七',
    'shortname' => '',
    'hitsid' => 'c-1-67',
    'views' => '5',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '4',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '9',
    'typeid' => '59,60',
    'title' => '漫畫介紹－聖哥傳（11）',
    'style' => '',
    'thumb' => 'http://pic0.mofang.com/2015/1013/20151013094208696.jpg',
    'keywords' => ' 聖☆おにいさん,聖哥傳',
    'description' => '漫畫介紹－聖哥傳（11）　（聖☆おにいさん 11）　　當大家認為高高在上的「神」來到人間，會過著怎麼樣的生活呢？而努力想融入人間界的他...',
    'posids' => '1',
    'url' => 'http://www.spatialgate.com.tw/comic/9-81-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443416359',
    'updatetime' => '1447319551',
    'authorname' => '歿子',
    'shortname' => '',
    'hitsid' => 'c-1-81',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  130 => 
  array (
    'id' => '130',
    'catid' => '9',
    'typeid' => '59',
    'title' => '漫畫介紹－惡之娘：第二幕',
    'style' => '',
    'thumb' => 'http://pic2.mofang.com/2015/1013/20151013103752599.gif',
    'keywords' => ',惡之娘, 悪ノP, NICO',
    'description' => '　　「惡之」系列是相當特殊的作品，原來是NICONICO上的一系列歌曲，先是改編成輕小說後，再從小說之中截取重點劇情繪制成漫畫。本作「惡之...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/comic/9-130-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443421634',
    'updatetime' => '1447319147',
    'authorname' => '',
    'shortname' => '',
    'hitsid' => 'c-1-130',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  114 => 
  array (
    'id' => '114',
    'catid' => '9',
    'typeid' => '60',
    'title' => '漫畫介紹－幽界靈語 （04）',
    'style' => '',
    'thumb' => 'http://pic1.mofang.com/2015/1013/20151013101704877.jpg',
    'keywords' => '藤崎竜, 幽界靈語,',
    'description' => '漫畫介紹－幽界靈語 （04）　　時間是架空的現代日本，人們與靈魂的距離十分微妙，藉由每一代「公主」的靈力，能將死去的偉大靈魂們從黃泉...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/comic/9-114-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443421084',
    'updatetime' => '1447319157',
    'authorname' => '歿子',
    'shortname' => '',
    'hitsid' => 'c-1-114',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
);
?>