<?php
return array (
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首頁﹣輪播圖',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首頁﹣推薦文章',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '98',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首頁﹣推薦列表',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '97',
    'siteid' => '1',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页头条推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-專欄',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-動畫',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-小說',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-漫畫',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-遊戲',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '3',
    'catid' => '0',
    'name' => '编辑推荐-cosplay',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-新聞',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-活動',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '3',
    'catid' => '0',
    'name' => '編輯推薦-萌圖',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '1',
    'catid' => '0',
    'name' => '编辑推荐-周邊',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '82',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '69',
    'catid' => '0',
    'name' => '推荐下载',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '30',
    'catid' => '54',
    'name' => '图片频道首页焦点图',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '1',
    'catid' => '16',
    'name' => '精選專欄',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页每日热点',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频栏目精彩推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>