<?php return array (
  'name' => '台湾站新模版',
  'author' => 'MOFANG TEAM',
  'dirname' => 'tw_mofang',
  'homepage' => 'http://www.mofang.com.tw/',
  'version' => '1.0',
  'disable' => 0,
  'file_explan' => 
  array (
    'templates|v4|tw_mofang' => 
    array (
      'category.tpl' => '文章頻道頁',
      'category_video.tpl' => '视频頻道頁',
      'category_download.tpl' => '下載頻道頁',
      'category_picture.tpl' => '圖片頻道頁',
      'download.tpl' => '下載連接頁',
      'footer.tpl' => '底部',
      'header.tpl' => '頂部',
      'header_min.tpl' => '迷你頂',
      'header_page.tpl' => '單網頁頭部',
      'index.tpl' => '網站首頁',
      'list.tpl' => '列表頁',
      'list_video.tpl' => '视频列表頁',
      'list_user.tpl' => '用户文章列表頁',
      'list_zone.tpl' => '专区列表頁',
      'list_download.tpl' => '下載列表頁',
      'list_picture.tpl' => '圖片列表頁',
      'message.tpl' => '消息提示頁',
      'page.tpl' => '單網頁',
      'rss.tpl' => 'RSS頁',
      'search.tpl' => '搜索',
      'show.tpl' => '文章內容頁',
      'show_video.tpl' => '视频內容頁',
      'show_download.tpl' => '下載內容頁',
      'show_picture.tpl' => '圖片內容頁',
      'tag.tpl' => 'tag',
    ),
  ),
);?>
