<?php
return array (
  58 => 
  array (
    'typeid' => '58',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '輕小說',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  59 => 
  array (
    'typeid' => '59',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '漫畫',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  60 => 
  array (
    'typeid' => '60',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '動畫',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  61 => 
  array (
    'typeid' => '61',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '心得',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  62 => 
  array (
    'typeid' => '62',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '周邊商品',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  63 => 
  array (
    'typeid' => '63',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '手機遊戲',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  64 => 
  array (
    'typeid' => '64',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '經典',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  67 => 
  array (
    'typeid' => '67',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '遊戲',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  68 => 
  array (
    'typeid' => '68',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '遊記',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  69 => 
  array (
    'typeid' => '69',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => 'cosplay',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  70 => 
  array (
    'typeid' => '70',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '聲優',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  71 => 
  array (
    'typeid' => '71',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '話題',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  72 => 
  array (
    'typeid' => '72',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '特攝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
);
?>