seajs.config({
    "alias": {
        "debug": "/statics/v4/modules/js/mfe/debug.js",

        "underscore": "/statics/v4/modules/js/underscore.js",
        "zepto": "/statics/v4/modules/js/zepto.js",
        "base64": "/statics/v4/modules/js/base64.js",
        "atom": "/statics/v4/modules/js/atom.js",

        "jquery": "/statics/v4/modules/js/jquery/jquery.js",
        "scrollUp": "/statics/v4/modules/js/jquery/scrollUp.js",
        "jquery/jq_cookie": "/statics/v4/modules/js/jquery/jquery.cookie.js",

        "jquery/ui": "/statics/v4/modules/js/jquery/ui.js",
        "jquery/bxslider": "/statics/v4/modules/js/jquery/bxslider.js",
        "jquery/roundRank": "/statics/v4/modules/js/jquery/roundRank.js",
        "jquery/Slider": "/statics/v4/modules/js/jquery/carsouse.js",
        "jquery/video": "/statics/v4/modules/js/jquery/video.js",
        "jquery/cookie": "/statics/v4/modules/js/jquery/cookie.js",
        "jquery/json": "/statics/v4/modules/js/jquery/json.js",
        "jquery/migrate": "./jquery/migrate.js",
        "jquery/tabs": "/statics/v4/modules/js/jquery/tabs.js",
        "jquery/transform2d": "/statics/v4/modules/js/jquery/transform2d.js",
        "jquery/scrollbox": "/statics/v4/modules/js/jquery/scrollbox.js",
        "jquery/carousel": "/statics/v4/modules/js/jquery/carousel.js",
        "jquery/flexslider": "/statics/v4/modules/js/jquery/flexslider.js",
        "jquery/nicescroll": "/statics/v4/modules/js/jquery/jquery.nicescroll.min.js",
        "jquery/sUP": "/statics/v4/modules/js/jquery/jquery.scrollUp.min.js",
        "jquery/urldecoder": "/statics/v4/modules/js/jquery/jquery.urldecoder.min.js",
        "jquery/easing": "/statics/v4/modules/js/jquery/easing.js",
        "jquery/livequery": "/statics/v4/modules/js/jquery/livequery.js",
        "swipe": "/statics/v4/modules/js/jquery/swipe.js",
        "jquery/transit": "/statics/v4/modules/js/jquery/jquery.transit.js",
        "jquery/query": "/statics/v4/modules/js/jquery/query.js",
        "jquery/iscroll": "/statics/v4/modules/js/jquery/iscroll.js",
        "jquery/Swiper": "/statics/v4/modules/js/jquery/swiper.js",
        "jquery/Swiper3":"/statics/v4/modules/js/jquery/swiper3.js",
        "jquery/easings": "/statics/v4/modules/js/jquery/jquery.easings.min.js",
        "jquery/slimscroll": "/statics/v4/modules/js/jquery/jquery.slimscroll.min.js",
        "jquery/fullpage": "/statics/v4/modules/js/jquery/fullpage.js",
        "jquery/validate": "/statics/v4/modules/js/jquery/jquery.validate.js",
        "jquery/form": "/statics/v4/modules/js/jquery/jquery.form.js",
        "jquery/rotate":"/statics/v4/modules/js/jquery/jQueryRotate.js",

        "skrollr": "/statics/v4/modules/js/mfe/skrollr.min.js",
        "countdown": "/statics/v4/modules/js/mfe/countdown.js",
        "skrollr-ie": "/statics/v4/modules/js/mfe/skrollr.ie.min.js",

        "mfe": "/statics/v4/modules/js/mfe/mfe.js",
        "mfe/wheel": "/statics/v4/modules/js/mfe/wheel.js",
        "mfe/ui": "/statics/v4/modules/js/mfe/ui.js",

        "swfobject": "/statics/v4/modules/js/swfobject/swfobject.js",
        "luckydraw":"/statics/v4/modules/js/mfe/luckydraw.js",
        "widget": "/statics/v4/modules/js/mfe/widget.js",
        "tabs": "/statics/v4/modules/js/mfe/tabs.js",
        "tips": "/statics/v4/modules/js/mfe/tips_mod.js",
        "share": "/statics/v4/modules/js/mfe/mfshare.js",
        "dialog": "/statics/v4/modules/js/mfe/dialog.js",
        "card": "/statics/v4/modules/js/mfe/card.js",
        "carouses": "/statics/v4/modules/js/mfe/carouses.js",
        "hiteggs": "/statics/v4/modules/js/mfe/hiteggs.js",
        "eggsui": "/statics/v4/modules/js/mfe/eggsui.js",
        "handlebars": "/statics/v4/modules/js/mfe/handlebars.js",
        "ad": "/statics/v4/modules/js/ad.js",
        "jquery/sliderMf": "/statics/v4/modules/js/mfe/jquery.slider.mf.js",
        "jquery/amplifyImg": "/statics/v4/modules/js/mfe/jquery.pic.amplify.js",
        "mfe/wapLoadMore":"/statics/v4/modules/js/mfe/wapLoadMore.js",

        "moveTop": "/statics/v4/modules/js/mfe/moveTop.js",
        "fastclick": "/statics/v4/modules/js/mfe/fastclick.js",
        "jquery/jquery-pop":"/statics/v4/modules/js/mfe/jquery.pop.js",
        "jquery/jquery-slider-down":"/statics/v4/modules/js/mfe/jquery.slider.down.js",
        "jquery/jquery-reluserurl":"/statics/v4/modules/js/mfe/jquery.reluserurl.js",
        "mfe/isApp":"/statics/v4/modules/js/mfe/isApp.js",
        "lang/zh-cn":"/statics/v4/modules/js/lang/zh-cn.js",
        "lang/zh-tw":"/statics/v4/modules/js/lang/zh-tw.js",
        "lang/en":"/statics/v4/modules/js/lang/en.js",
        "lang/th":"/statics/v4/modules/js/lang/th.js",
        "lang/jp":"/statics/v4/modules/js/lang/jp.js",
        "jquery/fancybox":"/statics/v4/modules/js/jquery/jquery.fancybox.js",
        "hybridH5":"/statics/v4/modules/js/mfe/hybrid_h5.js"


    }
});
