<?php
return array (
  346 => 
  array (
    'id' => '346',
    'catid' => '6',
    'typeid' => '60',
    'title' => '《受讚頌者》新作動畫PV公佈',
    'style' => '',
    'thumb' => 'http://pic0.mofang.com/2015/0828/20150828111313123.jpg',
    'keywords' => '受讚頌者,動畫新聞,うたわれるもの,偽りの仮面',
    'description' => '　　AQUAPLUS高人氣的遊戲《受讚頌者》最新作品《受讚頌者虛偽的假面》（うたわれるもの偽りの仮面）將在9月24日PS4 ／ PS3 ／ PS Vit...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/anime/6-346-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443593981',
    'updatetime' => '1447319621',
    'authorname' => '',
    'shortname' => '',
    'hitsid' => 'c-1-346',
    'views' => '21',
    'yesterdayviews' => '14',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1099 => 
  array (
    'id' => '1099',
    'catid' => '6',
    'typeid' => '60,61',
    'title' => '季中心得－魯邦三世 新系列',
    'style' => '',
    'thumb' => 'http://pic1.mofang.com/2015/1109/20151109121429341.gif',
    'keywords' => '心得, 魯邦三世 新系列, TMS Entertainment,',
    'description' => '季中心得－魯邦三世 新系列（ルパン三世 新シリーズ）　　《魯邦三世新系列》的製作組「TMS Entertainment」，曾製作過魯邦三世系列的番...',
    'posids' => '1',
    'url' => 'http://www.spatialgate.com.tw/anime/6-1099-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'r7761620',
    'inputtime' => '1447042419',
    'updatetime' => '1447319001',
    'authorname' => '莓果柚子',
    'shortname' => '魯邦三世 新系列',
    'hitsid' => 'c-1-1099',
    'views' => '13',
    'yesterdayviews' => '0',
    'dayviews' => '13',
    'weekviews' => '13',
    'monthviews' => '13',
  ),
  968 => 
  array (
    'id' => '968',
    'catid' => '6',
    'typeid' => '60',
    'title' => '動畫介紹－牙狼 －紅蓮之月－',
    'style' => '',
    'thumb' => 'http://pic2.mofang.com/2015/1022/20151022032836312.jpg',
    'keywords' => '動畫介紹, 牙狼 －紅蓮之月－, 桂正和, ',
    'description' => '動畫介紹－牙狼 －紅蓮之月－（日文名：牙狼 －紅蓮ノ月－）　　《牙狼 －紅蓮之月－》是由特攝影集展開的動畫故事，這次的人設找來了虎...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/anime/6-968-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'r7761620',
    'inputtime' => '1445498856',
    'updatetime' => '1447308723',
    'authorname' => '小兔老師',
    'shortname' => '牙狼 －紅蓮ノ月－',
    'hitsid' => 'c-1-968',
    'views' => '10',
    'yesterdayviews' => '0',
    'dayviews' => '8',
    'weekviews' => '8',
    'monthviews' => '9',
  ),
  783 => 
  array (
    'id' => '783',
    'catid' => '6',
    'typeid' => '60',
    'title' => '推理型動畫《全部成為FTHE PERFECT INSIDER》',
    'style' => '',
    'thumb' => 'http://pic1.mofang.com/2015/0925/20150925112059924.jpg',
    'keywords' => '全部成為F, 森博嗣, 動畫介紹,すべてがFになる',
    'description' => '　　日北小說家「森博嗣」第一部推理小說作品《全部成為F》改編成動畫《全部成為FTHE PERFECT INSIDER》 （すべてがFになる），動畫即將...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/anime/6-783-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443672670',
    'updatetime' => '1446481308',
    'authorname' => '',
    'shortname' => '',
    'hitsid' => 'c-1-783',
    'views' => '10',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  302 => 
  array (
    'id' => '302',
    'catid' => '6',
    'typeid' => '59,60',
    'title' => '3DS主題桌布－[暗殺教室]テーマの時間2',
    'style' => '',
    'thumb' => 'http://pic1.mofang.com/2015/0616/20150616055503666.jpg',
    'keywords' => '暗殺教室,テーマの時間',
    'description' => '『暗殺教室』於任天堂3DS平台推出主題桌布－『[暗殺教室]テーマの時間2』！　　人氣作品『暗殺教室』於3DS平台推出系列主題桌布[暗殺教室]...',
    'posids' => '0',
    'url' => 'http://www.spatialgate.com.tw/anime/6-302-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => '小胖',
    'inputtime' => '1443501156',
    'updatetime' => '1447326544',
    'authorname' => '歿子',
    'shortname' => '',
    'hitsid' => 'c-1-302',
    'views' => '9',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>